### ISSUE TITLE
Conflict with Nova BelongsToMany component

### ISSUE THREAD

**Issue by zareismail** [everestmx/nova-belongs-to-many-field#1]
This field has a conflict with laravel nova `BelongsToMany` field component because the used component name is same as nova  component name

**Comment by everestmx** [comment]
> This field has a conflict with laravel nova `BelongsToMany` field component because the used component name is same as nova component name

Yes, i know this conflict. I'm already renamed component to the `belongs-to-many-tags`. Please, update to 0.0.4 version.
