### ISSUE TITLE
Issue with validation

### ISSUE THREAD

**Issue by susyzan** [everestmx/nova-belongs-to-many-field#4]
The **message()** is not implemented in the **ArrayRules class**, I am getting this error when I try to add validation:
` "Class Everestmx\BelongsToManyField\Rules\ArrayRules contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Validation\Rule::message)"`

Also **messages()** is being called but not implemented.

Any plans on fixing this in the future or is this package no longer maintained?

Thanks :)

**Comment by everestmx** [comment]
Please, use https://github.com/Benjacho/belongs-to-many-field-nova

**Comment by susyzan** [comment]
Thank you!
